### ISSUE TITLE
Bug - Web - [Marginal]- Mensaje de error - Ubicación, sólo con nombre

### ISSUE THREAD

**Issue by jmoreira18** [calisetpis2019/app.caliset#10]
Es posible crear de alta una Ubicación que sólo tiene nombre:
![image](https://user-images.githubusercontent.com/31781992/65821051-e91a3200-e206-11e9-9f6b-afbe53d7d8ba.png)
Luego esta es guardada de esta forma (se llenan por defecto estos datos):
![image](https://user-images.githubusercontent.com/31781992/65821056-f59e8a80-e206-11e9-936f-16bfe30235e6.png)

**Comment by Nestoter** [comment]
Pronto! Agregado como campos obligatorios los requeridos.
