### ISSUE TITLE
Bug - Web - [Menor*3] Nombre repetido cliente, Tipo de operación, Ubicación

### ISSUE THREAD

**Issue by jmoreira18** [calisetpis2019/app.caliset#11]
Es posible crear clientes con nombres repetidos, el nombre del cliente debería de ser único, porque si no es imposible diferenciarlos, o se pueden crear varios (que tendrían diferentes ids en la BD).
![image](https://user-images.githubusercontent.com/31781992/65820971-e8cd6700-e205-11e9-9264-8bafdcdc2626.png)

Lo mismo pasa para tipo de operación y ubicación.

**Comment by beissoNNN** [comment]
resuelto
