### ISSUE TITLE
Bug - Web - [Menor] - Mensaje de error - Usuario repetido

### ISSUE THREAD

**Issue by jmoreira18** [calisetpis2019/app.caliset#14]
Al dar de alta un usuario con mail repetido el error se muestra en inglés:
![image](https://user-images.githubusercontent.com/31781992/65820766-6479e480-e203-11e9-9509-d638cbf04f0d.png)

**Comment by Salameboy** [comment]
Se hablo con backend para que envio los mensajes de respuesta en español.

**Comment by Nestoter** [comment]
@beissoNNN @jmoreira18 Esto es de Backend, tienen que hablarlo con ellos o con Agustina para que lo arreglen.

**Comment by beissoNNN** [comment]
@vikgonb @fedeGodCamm @Eldkaii

**Comment by fedeGodCamm** [comment]
Quedo solucionado

**Comment by beissoNNN** [comment]
El mensaje de error simplemente dice que falló la creación del usuario. 
Es esperable que se informe el por qué.
El mensaje debería decir que el usuario que se quiere registrar ya existe en el sistema.

**Comment by fedeGodCamm** [comment]
Quedaron diferenciados los mensajes.
