### ISSUE TITLE
Bug - Web - [Marginal] - Alta de usuario sin campos obligatorios

### ISSUE THREAD

**Issue by jmoreira18** [calisetpis2019/app.caliset#15]
Se dio de alta con éxito un usuario con estos campos llenos únicamente (sin Rol):
![image](https://user-images.githubusercontent.com/31781992/65820691-7313cc00-e202-11e9-894c-44daef792905.png)
![image](https://user-images.githubusercontent.com/31781992/65820694-78711680-e202-11e9-8924-a7cf404e60aa.png)
El usuario pudo darse de alta y al querer editarlo vemos esto:
![image](https://user-images.githubusercontent.com/31781992/65820709-a191a700-e202-11e9-925a-743534aa71f2.png)
Campos que no se llenaron que tienen ahora datos por defecto. (Los demás datos están correctos)

**Comment by Salameboy** [comment]
Se hizo que Documento sea un campo obligatorio (como lo dice la HU), ahora no puede ser vacio.

**Comment by Salameboy** [comment]
Se hizo que rol sea obligatorio.
