### ISSUE TITLE
Bug - Mobile - [Menor] Nuevas contraseñas ingresadas tras primer logueo no coinciden

### ISSUE THREAD

**Issue by beissoNNN** [calisetpis2019/app.caliset#18]
Se inicia sesión por primera vez con un usuario.
Se acepta términos y condiciones.
Se solicita cambiar la password.
En password nueva se ingresa: testpass12345678
En reingresar nueva password: testpass12345678
Se modifica la primera ingresada a: Otrapassword12345678

Se permite el ingreso al sistema pero la nueva contraseña ingresada y el reingreso de la contraseña no coinciden.
La contraseña que queda registrada para el usuario es Otrapassword12345678.

**Comment by massi12** [comment]
No estoy pudiendo replicar el problema.
Si alguna de las dos contraseñas nuevas no coinciden, el botón para "Confirmar" no está habilitado... Seguro fueron esos los datos de contraseña que usaste?

**Comment by massi12** [comment]
Edite tu reporte del bug para unos datos que si replican el problema.

**Comment by sferrando89** [comment]
Corregido. Va en la próxima liberación.

**Comment by sferrando89** [comment]
Se corrige en el siguiente TAG:

https://github.com/calisetpis2019/mobile.caliset/releases/tag/23_Bug18
