### ISSUE TITLE
Bug - Web - [Menor] - Mensajes/Botones/textos incorrectos

### ISSUE THREAD

**Issue by beissoNNN** [calisetpis2019/app.caliset#23]
Mensaje de "LoginPrompt" cuando estás iniciando sesión.
Botón "Assign" cuando se desea asignar usuario a una operacion.

**Comment by Salameboy** [comment]
Se cambio el texto "loginPrompt" a "Iniciando sesión".
Se cambio el texto "Assign" a "Asignar".
