### ISSUE TITLE
Bug - Web - [Menor] - Mensaje de Superposición

### ISSUE THREAD

**Issue by beissoNNN** [calisetpis2019/app.caliset#24]
Se realiza la asignación pero no se notifica al responsable.
Al inspector asignado le aparece en "Nuevas Operaciones" para confirmarla o rechazarla, pero no recibe notificacion. 
"...El sistema confirma la asignación y se envía una notificación (por cada asignación) con el mensaje “Usted fue asignado a la Operación” con los datos obligatorios de la misma y los datos de cada asignación que se realizó al usuario. "

Si surge el caso de superposicion no se alerta de la misma.  ".. Se muestra una alerta con el mensaje “SUPERPOSICIÓN: El inspector está asignado a otra Operación” con los datos obligatorios de la misma."

**Comment by massi12** [comment]
La app mobile está apta para recibir las notificaciones de cualquier tipo, cuando el usuario está logueado

**Comment by Nestoter** [comment]
@beissoNNN no me queda claro si acá interviene FW.
Cuando dice:

 Si surge el caso de superposicion no se alerta de la misma. ".. Se muestra una alerta con el mensaje “SUPERPOSICIÓN: El inspector está asignado a otra Operación” con los datos obligatorios de la misma."

¿Ese mensaje de superposición es para el que está realizando la asignación?

**Comment by beissoNNN** [comment]
@Nestoter Entiendo que es para el que está realizando la asignación si, y le salta la alerta en la web. La HU no está muy clara en realidad. Ahí averiguo bien.

**Comment by Nestoter** [comment]
@beissoNNN le pedimos al Back que nos devuelva la información que necesitamos para mostrar el cartel:
"necesitamos que el servicio /api/services/app/Assignation/Create en caso finalizar de forma correcta, nos devuelva una variable en true si la asignación de este inspector se solapa con alguna otra asignación que tiene este inspector, o false en caso contrario"

**Comment by Eldkaii** [comment]
Pronto.

**Comment by Nestoter** [comment]
@beissoNNN bo, esto está casi pronto, pero no me percaté del final

Si surge el caso de superposicion no se alerta de la misma. ".. Se muestra una alerta con el mensaje “SUPERPOSICIÓN: El inspector está asignado a otra Operación” con los datos obligatorios de la misma." 

¿Que son los datos obligatorios de la misma? Si son los datos de la Operacion, ¿Que aparece si hay superposicion con 2 asignaciones de 2 operaciones distintas?

**Comment by Nestoter** [comment]
Ahora está hecho de que si hay superposición aparece un carte que te dice que la asignación que acabas de hacer se superpone con otra.

**Comment by beissoNNN** [comment]
![image](https://user-images.githubusercontent.com/29243394/67729697-e1e66f80-f9d0-11e9-9dba-a23b414d67b0.png)

Los datos obligatorios son los de la operación a la que se superpone. O sea, a la que ya estaba asignado.

"¿Que aparece si hay superposicion con 2 asignaciones de 2 operaciones distintas?"
Asumo que lo que interesa es informar a qué operaciones se superpone. En ese caso deberían mostrarse los datos de ambas, o que se desplieguen 2 alertas de superposicion una tras otra capaz. @Nestoter
