### ISSUE TITLE
[SEMANA 9 Y 10]  Web - [Marginal] - Comentario Operacion - no se actualiza estado que se finalizó desde otro navegador y permite comentar igual

### ISSUE THREAD

**Issue by beissoNNN** [calisetpis2019/app.caliset#28]
1-Entro al listado de operaciones en el sistema.
2-Se finaliza una operación desde otro usuario en otro navegador.
3-Listado de operaciónes en mi navegador aún no se actualiza y la operacion sigue figurando como NO finalizada, y permite seleccionar boton "comentar".
4- Intento realizar comentario y se crea, cuando en realidad no se podria ya que la operacion es finalizada

**Comment by Nestoter** [comment]
@beissoNNN  Buenas, esto lo tiene que controlar Backend. Nosotros desde el front, si no se actualiza la página, no tenemos forma de controlarlo.

**Comment by beissoNNN** [comment]
@vikgonb @fedeGodCamm @Eldkaii

**Comment by Eldkaii** [comment]
Quedo solucionado.
