### ISSUE TITLE
[SEMANA 9 Y 10] Web - [Menor] - Eliminar Operación - Permite eliminar operacion a un operador

### ISSUE THREAD

**Issue by beissoNNN** [calisetpis2019/app.caliset#29]
Un operador no deberia poder eliminar la operacion, solo el Admin

**Comment by Nestoter** [comment]
@beissoNNN ¿Como fue esto? ¿A un usuario Operador le aparecía el botón de eliminar Operación en el FW?
Lo que está ahora programado el rol Operador no ve nada en el sistema, si lo dejó debería haber sido Administrador además de Operador.

**Comment by beissoNNN** [comment]
@Nestoter Si, le aparece el botón. Lo hice con el usuario Operador3erLiber que es solamente operador.
Te dejo las credenciales para que lo veas en la version subida al server.
user: Operador3erLiber@gmail.com
pass: Operador3erLiber

**Comment by beissoNNN** [comment]
@Nestoter esta andando bien pero el mensaje de error apenas se muestra una milesima de segundo jajaj

**Comment by beissoNNN** [comment]
paso la issue a menor nomas
