### ISSUE TITLE
[SEMANA 9 Y 10] Web+Mobile - [Menor*2] - Editar contraseña - Se permite la modificacion ingresando misma contraseña actual y nueva contraseña

### ISSUE THREAD

**Issue by beissoNNN** [calisetpis2019/app.caliset#31]
La HU especifica que la contraseña actual ingresada y la nueva contraseña ingresada deben de ser distintas.
Pasa tanto en web como en mobile. 
En mobile hay mensaje alertando sobre contraseñas iguales, pero se permite modificar igual y quedando iguales.

**Comment by massi12** [comment]
En mobile si las contraseñas "actual" y "nueva" coinciden, te muestra un mensaje _"La contraseña actual y la nueva son iguales y deben ser distintas."_ y no está habilitado el botón de confirmar... 
No pude replicar el error que mencionas!
Adjunto foto
![S91021-002001](https://user-images.githubusercontent.com/44514336/67174602-01f6ad00-f399-11e9-8414-f1283b09ef70.jpg)

**Comment by beissoNNN** [comment]
@massi12

**Comment by Nestoter** [comment]
Arreglado en FW
