### ISSUE TITLE
[SEMANA 9 Y 10] - Web - [Crítico] - Listar usuarios adicional filtros-Ver Usuarios-Listar Operaciones asignadas a un usuario- Operador no tiene lista de usuarios

### ISSUE THREAD

**Issue by beissoNNN** [calisetpis2019/app.caliset#33]
Desde un operador sólo se está pudiendo visualizar la pestaña de operaciones, no hay usuarios.

**Comment by Nestoter** [comment]
@beissoNNN ¿El Operador debe ver el botón de usuarios (del menú)? En caso afirmativo, ¿Cuales de los botones de Usuarios debe ver?
![image](https://user-images.githubusercontent.com/37219633/67418215-c0d0e980-f5a0-11e9-9239-5f937e5b3008.png)

**Comment by beissoNNN** [comment]
Fah no te sabría decir eso ahora. Tendría que revisar las HU que implementaron para ver que funcionalidades puede hacer el Operador. Lo puedo ver en otro momento.

**Comment by beissoNNN** [comment]
Editar sacalo porque solo puede el admin. (qué pasaría si hay un usuario administrador y operador al mismo tiempo? igual no se si eso pasaria en la realidad)
Eliminar, lo mismo, sacalo.
Concluyendo, solo tendría el boton ver. @Nestoter

**Comment by Salameboy** [comment]
Listo, ahora para los operadores solo se lista el boton de ver y para los administradores el de ver, editar y eliminar.
