### ISSUE TITLE
[SEMANA 9 Y 10] - Web - [Marginal] - Borrar usuario - Permite autoborrarse a un administrador. Y borrar usuario con sesión activa

### ISSUE THREAD

**Issue by beissoNNN** [calisetpis2019/app.caliset#34]
Se autoborra y queda en vista dentro del sistema pero sin sesión activa, y no permite ir a vista de login.
En mi opinión no debería dejar autoborrarse. O sino que se permita pero que lo redireccione a vista de login. sino no puede volver a ingresar al sistema.

Pasa lo mismo cuando se borra a un usuario que esta con sesion activa. Debería redireccionarse a ventana de login.

**Comment by Nestoter** [comment]
Sacamos los botones de borrar para el usaurio que está logueado y el boton de desactivar cuando se intenta editar al usuario que está logueado. Queda ver el redirect al login.

**Comment by Nestoter** [comment]
@beissoNNN quedó. En caso de que un usuario esté logueado y alguien mas lo elimine, mientras no se consulte al Backend el usuario eliminado no se entera. No podemos hacer que lo patee automáticamente, lo que si pasa es que cuando el usuario eliminado consulta al Back, le aparece este cartel:
![image](https://user-images.githubusercontent.com/37219633/67338679-08ebff80-f500-11e9-9b30-3a391cf5f6d2.png)
El usuario puede hacer logout de forma normal, ahi lo lleva al login.

Para el caso que el usuario se deshabilita, el usuario puede seguir trabajando. Se debe agregar un control en el Backend que no permita ejecutar nada a usuarios que no están activos. Poniendo ese control, pasaría lo mismo que cuando el usuario se elimina.

**Comment by beissoNNN** [comment]
> Sacamos los botones de borrar para el usaurio que está logueado y el boton de desactivar cuando se intenta editar al usuario que está logueado. Queda ver el redirect al login.

No entendi eso del boton desactivar, no veo ninguno. @Nestoter

**Comment by Eldkaii** [comment]
Creo que lo corregí, si alguien de Web lo prueba y me confirma mejor.

**Comment by beissoNNN** [comment]
No hay forma de hacer que se desloguee automáticamente? En mobile se propuso que se mandara cierto tipo de mensaje desde el back y que en ese caso se desloguee, no se si lo terminaron solucionando así ellos. 

Luego, lo de deshabilitar el usuario sigue igual, puede seguir haciendo cosas aunque se lo deshabilite. De todas formas, eso de usuario deshabilitado no aparece en ninguna HU, ni vi que se especificara en ningun lado. Capaz ni debería estar implementado. Matías especificó algo acerca de esto por otra parte?
