### ISSUE TITLE
Web - [Menor] - Editar operación - En operaciones finalizadas se da la opcion de editar

### ISSUE THREAD

**Issue by beissoNNN** [calisetpis2019/app.caliset#36]
Si bien no se permite realizar la modificacion una vez que se trata de confirmar, no tiene sentido que se de la opcion de editar. Ademas que se muestran muy pocos campos en el formulario no se por qué

**Comment by Nestoter** [comment]
Pronto!

**Comment by Nestoter** [comment]
Pronto!

**Comment by Nestoter** [comment]
@beissoNNN bo, especificamente hay una tarjeta que dice que se debe poder editar la información de una Operación finalizada con el usuario Administrador. Le solamente esta opción al Administrador.
![image](https://user-images.githubusercontent.com/37219633/67419494-2cb45180-f5a3-11e9-8ee0-afd8df2df318.png)

**Comment by Nestoter** [comment]
SI, semana 11 y 12.

**Comment by beissoNNN** [comment]
(se me mando el mensaje solo xP)
El bug salió de una de semana 7 y 8, de la HU Editar Datos operacion.
Esa decía que un operador no puede editar una operacion finalizada, y como se suponia que el admin tiene mismos permisos que el operador pensé que corria la restriccion para el admin tambien.
En conclusion, las operaciones finalizadas solo las puede editar el admin, los operadores no.

**Comment by Nestoter** [comment]
Pronto!
