### ISSUE TITLE
BUG DEMO - Web - [Menor] - Editar operación - Cambio de fecha de inicio no cambia estado de la operacion

### ISSUE THREAD

**Issue by beissoNNN** [calisetpis2019/app.caliset#37]
La HU especifica " Si se modifica Fecha y hora de inicio, el estado de la operación cambiará o no dependiendo de los datos ingresados."

Se cambió la fecha de inicio a una anterior a la actual y el estado se mantiene en futura.
Se cambió una activa a fecha de inicio mas adelante y se mantiene en activa.

**Comment by Nestoter** [comment]
@beissoNNN Backend tiene que aplicar la misma lógica en Editar. Cuando se manda un cambio de fecha y amerita algún cambio de estado, se debe hacer en esa misma llamada de Editar Operación.

**Comment by Eldkaii** [comment]
Pronto

**Comment by beissoNNN** [comment]
Falta que cuando a una operacion futura se le cambia fecha de inicio a una mas vieja que la fecha actual del sistema, se cambie de estado futura a activa.

**Comment by Eldkaii** [comment]
Eso lo hace el demonio solo

**Comment by beissoNNN** [comment]
Pero el caso era si uno quería modificar manualmente la fecha de una operación. Cuando lo probé se mantuvo el estado futura.

**Comment by Eldkaii** [comment]
Ya lo cambia automáticamente.
