### ISSUE TITLE
BUG DEMO - Web - [Menor] - Ver operaciones

### ISSUE THREAD

**Issue by beissoNNN** [calisetpis2019/app.caliset#38]
1-Se debe contar con 3 tablas de Operaciones (1 por estado)
2-La tabla de Op Activas y Futuras debe estar ordenada por fechaInicioOp de la más reciente a la más futura. (creciente)
3-La tabla de Op Finalizadas debe estar ordenada por fechaInicioOp al revés al criterio anterior (decreciente)

**Comment by Nestoter** [comment]
Pronto!
