### ISSUE TITLE
BUG DEMO - Web - [Menor] - Ver operaciones, Usuarios asignados

### ISSUE THREAD

**Issue by beissoNNN** [calisetpis2019/app.caliset#39]
La tabla "Usuarios Asignados" debe llamarse "Asignaciones"

Agregar columnas: FechaInicio Asignación y Estado de Asignación (si aceptó o rechazó)

Si asigno 2 veces el mismo usuario a una Op en fechas distintas, deben aparecer 2 filas

**Comment by Nestoter** [comment]
@Salameboy @sferrando89 che, estoy viendo y esto parece que está pronto. ¿Alguien de ustedes lo hizo?
