### ISSUE TITLE
BUG DEMO - Web - [Menor] - Ver operaciones, Muestras

### ISSUE THREAD

**Issue by beissoNNN** [calisetpis2019/app.caliset#40]
Agregar columnas IdMuestra - Nota - Fecha - Nombre y Apellido de quién la registró

**Comment by Nestoter** [comment]
Solicitada nueva funcionalidad a Backend.

Buenas @Victoria González @Emilio Méndez @federico godoy, por bug #40 necesitamos que se agreguen varios campos a las funcionalidades de getSample.
En particular, necesitamos el fullName del usuario creador de la Sample y la creationTime
Como ejemplo les paso el getComment, un estilo así alcanzaría:
{
     "id": 2,
     "commentary": "xD2",
     "creatorUser": {
       "id": 2,
       "name": "admin",
       "surname": "admin",
       "emailAddress": "admin@defaulttenant.com",
       "phone": "123"
     },
     "creationTime": "2019-10-23T13:12:36.955291"
   }

**Comment by beissoNNN** [comment]
ese emilio que tageaste es de Berlín

**Comment by beissoNNN** [comment]
@fedeGodCamm @vikgonb @Eldkaii
