### ISSUE TITLE
BUG DEMO - Web - [Menor] - Operaciones 

### ISSUE THREAD

**Issue by beissoNNN** [calisetpis2019/app.caliset#43]
Ver que quede ok la búsqueda por "Keyword" como en Usuario
Yo cambiaría "Keyword" por alguna otra palabra más amigable jajaja se les ocurre alguna?

**Comment by Nestoter** [comment]
@Salameboy ¿esta pronto no?

**Comment by beissoNNN** [comment]
no entendí esta @Salameboy
