### ISSUE TITLE
BUG DEMO - Web + MOBILE - [Crítico] - Notificaciones en general 

### ISSUE THREAD

**Issue by beissoNNN** [calisetpis2019/app.caliset#45]
- [ ] 1-Cuando se crea una op así como cuando se activa la misma se debe notificar al responsable asignado.

- [ ] 2-Cuando se edita una operación se debe notificar al responsable asignado

- [x] 3-Cuando se Asigna un Inspector se debe notificar al inspector

- [x] 4-Cuando se asigna un inspector para una fecha y ya está asignado a otra Op en esa fecha se manda una notificación de superposición al responsable

**Comment by Nestoter** [comment]
Buenas, ¿Por donde notificamos en el Fronted Web? No me queda claro que es lo que se espera exactamente.

**Comment by beissoNNN** [comment]
Con Nacho ya habiamos conversado eso un poco. Me habia dicho que iba a ver lo de las notificaciones en la campanita de la web. @Nestoter @Salameboy
