### ISSUE TITLE
[SEMANA 9 Y 10] - MOBILE - [Marginal] - Borrar usuario - Borrar inspector con session activa en mobile

### ISSUE THREAD

**Issue by beissoNNN** [calisetpis2019/app.caliset#46]
1-Existe inspector logueado en app mobile.
2-Borro con un admin al inspector
3- El inspector sigue dentro de la aplicacion y se le permite crear comentarios (los cuales no aparecen con su nombre y apellido, sino que con NUll Null), y registrar muestras.
Cuando se intenta modificar la contraseña y se da a confirmar, se recibe el mensaje "No se realizó el cambio. La respuesta vino vacía" y posteriormente se direcciona a ventana de login.

Lo que debería suceder es una vez borrado, cuando quiera hacer algo se lo envie a ventana de login.

El backend tendria que avisar de alguna manera que el usuario que esta logeadoo fue borrado. 
O sino que cuando quiera hacer algo desde la app y el back detecta que el usuario que pide ya no existe, tire un mensaje particular asi mobile puede controlarlo y saber que no existe mas, y tiene que cerrar sesion.

**Comment by massi12** [comment]
Hice unas pruebas y podría solucionarse mandando desde el back una notificación como al asignar o modificar una operación, modificandola un poco, quedando algo así:

{
     "data": {
       "msg": "Usuario borrado"
     },
     "priority": "High",
     "to": USER_DEVICE_TOKEN
}

Al recibir este mensaje en la app, cerraríamos sesión
@Eldkaii @fedeGodCamm @vikgonb

**Comment by massi12** [comment]
Quedó pronto para probar
