### ISSUE TITLE
[SEMANA 9 Y 10] - Web - [Menor] -Listar Operaciones asignadas a un Usuario - No se da opción de ver más detalles de la operación

### ISSUE THREAD

**Issue by beissoNNN** [calisetpis2019/app.caliset#47]
La HU dice, "Al clickear una fila se mostrará la información detallada de la operación correspondiente."

Que supongo que se refiere a que se ejecute la HU "Ver Operacion" implementada en semana 7 y 8

**Comment by Nestoter** [comment]
@beissoNNN bo esto es el boton "ver" que está en la fila de una operacion. Que tenemos que hacer¿

**Comment by beissoNNN** [comment]
Cuando entras a un usuario se despliega lista de operaciones a las cuales esta asignado, tendria que estar esa opción de ver. @Nestoter
