### ISSUE TITLE
[SEMANA 9 Y 10] Web - [Menor] - Eliminar Operación - Mensaje de error cuando se intenta borrar operación finalizada se ve muy rápido.

### ISSUE THREAD

**Issue by beissoNNN** [calisetpis2019/app.caliset#48]
Se intenta eliminar una operacion finalizada y apenas se llega ver el mensaje de error

**Comment by Nestoter** [comment]
¿Como es esto? ¿Que mensaje de error?

**Comment by Salameboy** [comment]
Es un mensaje de error que dice "Operacion finalizada, no se puede eliminar"
![Screenshot_2](https://user-images.githubusercontent.com/689049/67525146-7dea4100-f688-11e9-9709-c30be8d290c3.png)
Si tratas de eliminar una operacion finalizada desde swagger te da error.

**Comment by Salameboy** [comment]
No se si esta especificado en algun lugar, pero capaz que no se pueden eliminar operaciones finalizadas.
