### ISSUE TITLE
Mobile - [Menor] - Notificación mobile al Editar Operación

### ISSUE THREAD

**Issue by beissoNNN** [calisetpis2019/app.caliset#49]
La HU especifica lo siguiente:
"Criterio de Aceptación 1.1: Notificación exitosa
Se envía una notificación con un mensaje “Operación Modificada” con los datos que fueron modificados de la misma.
El sistema notifica al responsable de operación y a los inspectores asignados a la misma."

- [x] En mobile se está recibiendo la notificación pero sin los datos que fueron modificados de la misma. Y al abrirla te queda la vista en la pantalla principal, o sea no te enterás cuál fue modificada de todas las asignadas. Se debería al menos mostrar los datos en la notificación como pide la HU.

**Comment by Eldkaii** [comment]
Esta pronto. Si alguno lo puede probar si quedo bien ideal.

**Comment by beissoNNN** [comment]
@massi12 @sferrando89 lo vieron esto para mobile?

**Comment by beissoNNN** [comment]
Ahora se está recibiendo la notificación pero nada más se indican los nombres de los campos modificados y en inglés.
Lo que entiendo de la HU es que se deben imprimir el valor de los campos. O de alguna manera identificar la operación modificada, sino no tiene sentido la notificación. Se lo consulto a Matías en la demo.

**Comment by massi12** [comment]
Nosotros sólo recibimos la notificación, es imposible saber cual es la operación, que campos se modificaron y como cambiaron, sólamente desde la app.

**Comment by Eldkaii** [comment]
https://github.com/calisetpis2019/app.caliset/issues/49#issuecomment-547558878

Recién me di cuenta que puse las variables que cambian con el nombre que manejamos nosotros en vez del que se muestra.
Díganme cómo se llaman cada una y las pongo en español. También si quieren se puede agregar el valor nuevo que se modificó y el id de la operación.

**Comment by beissoNNN** [comment]
Tipo
Lugar
Fecha y hora de inicio
Responsable
Mercadería
Empaque
Nominador
Cargador
Nombre del barco
Destino
Referencia cliente
Linea
Numero de booking
Notas

Si querés andá agregando eso si, y el id de la operación capaz, si es que sirve para identificarla visualmente. Sino igual espera a que le consultemos a Matías porque no es muy especifica la HU.

**Comment by Eldkaii** [comment]
Ya le cambié todo eso, si alguno lo puede probar a ver si quedo ideal.

**Comment by massi12** [comment]
> 
> 
> Ya le cambié todo eso, si alguno lo puede probar a ver si quedo ideal.

Cuál es el id del commit?

**Comment by Eldkaii** [comment]
Ni idea pero es el último que hice y la descripción es bastante específica

**Comment by massi12** [comment]
Lo acabo de probar y se recibe bien la notificación, indicando el id de la operación y los datos que fueron modificados. 
Lo único que le agregaría sería un salto de línea entre cada atributo modificado para que sea más fácil la visualización.
