### ISSUE TITLE
Bug - Web- [Marginal] - Alta de operación (Notificaciones)

### ISSUE THREAD

**Issue by jmoreira18** [calisetpis2019/app.caliset#5]
Se dió de alta un estado y se fueron ingresando campos a medida que se pedían. Los mensajes de error indican que se esperan ciertos campos que no aparecen en el formulario. Tienen nombres diferentes.

Se tendría que permitir asignar un cliente a la operación y no existe ese campo.

Los campos obligatorios están mal. El estado ahora es obligatorio o opcional como en la HU documentada?

Se tendría que poder especificar hora de la operacion.

Faltan campos opcionales.

Una vez creada la operación, no se ve su estado. No se si se le asignó o no.

Las ubicaciones se ven por un id al parecer, y no por su nombre.

Los clientes se están pasando por Id en vez de por nombre:
![image](https://user-images.githubusercontent.com/31781992/65821273-ce958800-e209-11e9-92ff-f93fa3d22086.png)
 
El título del mensaje de error no tiene sentido en el contexto, no existe un cliente con el id (que debería de ser nombre) buscado.

Tmbién el título al entrar en la ventana de creacion de operacion dice "crear ubicacion".

**Comment by Salameboy** [comment]
Ya se puede asignar los dos clientes (nominador y cargador) a una operacion.
Se permite asignar la hora de la operacion.

Se agregaron todos los campos faltantes.

Se ve el estado como un texto en el listado de operaciones. Las ubicaciones aparecen por su nombre.

Se cambio donde antes decia ubicación por operación.

**Comment by Salameboy** [comment]
Ya se arreglaron los campos obligatorios.

**Comment by beissoNNN** [comment]
@Salameboy 
ISSUES UPDATE:
-La asociación con el cliente no se hace adecuadamente. Se está puediendo crear operación y asignarle un cliente que no existe en el sistema.

**Comment by Nestoter** [comment]
@beissoNNN veo lo de notificaciones. ¿Podes crear un bug nuevo para Backend con el tema del mensaje de error en inglés?

**Comment by beissoNNN** [comment]
> @beissoNNN veo lo de notificaciones. ¿Podes crear un bug nuevo para Backend con el tema del mensaje de error en inglés?

@Nestoter no entendí lo del mensaje en ingles.
Lo unico que queda arreglar en esta issue es la notif (está comentado más arriba como issue update):

-No le llega notificación al responsable de la operación. O sea, no se cumple:." Criterio de Aceptación 1.1: Notificación exitosa:
Se envía una notificación al responsable de la operación con el mensaje “Usted es Responsable de la Operación” con los datos obligatorios de la misma."
(igual no se tomaba en cuenta para la 1er liberación)

Esta es una de las notificaciones de esas que entrarian como notificacion en la web en la parte de la campanita .

**Comment by Nestoter** [comment]
Consulté a Canal (Slack) a ver que solución implementamos.

"che para el tema de las notificaciones en el FW al crear Operaciones'( https://github.com/calisetpis2019/app.caliset/issues/5 ) estuve pensando y se me ocurrieron 2 opciones:
1. WebSockets: abrir un canal con el Backend y cuando se cree una nueva Operacion deposite un mensaje con el idUsuario de los implicados
2. Pollear cada n segundos el Backend en busca de mensajes.
¿Que les parece?"

**Comment by vikgonb** [comment]
@Nestoter en boilerplate ya está implementado un módulo de notificaciones, habría que investigarlo. Desde back mandamos esas notificaciones, no se cómo las toma FW. Le estuve comentando algo a Nacho de esto.

**Comment by Nestoter** [comment]
@vikgonb bien, nos podes explicar como funciona? que tenemos que invocar?
