### ISSUE TITLE
Web - [Marginal] - Fechas en asignaciones

### ISSUE THREAD

**Issue by beissoNNN** [calisetpis2019/app.caliset#51]
Las asignaciones a una operacion deberian tener fecha y hora de inicio y fecha y hora de finalizacion iguales o posteriores a la fecha de inicio de la operacion. Actualmente se está permitiendo  ingresar fechas anteriores.

**Comment by beissoNNN** [comment]
Sigue permitiendose asignacion con fechas anteriores al comienzo de la operacion

**Comment by Salameboy** [comment]
Quedo pronto, se libero un commit en el que se habia borrado este arreglo.
