### ISSUE TITLE
Web - [Menor] - Fechas en ver operación

### ISSUE THREAD

**Issue by beissoNNN** [calisetpis2019/app.caliset#53]
Falta cambiar el formato adecuado de la fecha

**Comment by Nestoter** [comment]
@beissoNNN ¿Cual es el formato adecuado?

**Comment by beissoNNN** [comment]
Como había pedido Matías en la demo anterior, día, mes y año. Ahora está al revés.

**Comment by Nestoter** [comment]
Pronto
