### ISSUE TITLE
Web - [Menor] - Realizar comentario en oper finalizada con un Admin

### ISSUE THREAD

**Issue by beissoNNN** [calisetpis2019/app.caliset#54]
Las operaciones finalizadas solo las puede comentar un Admin y no se le está permitiendo.

**Comment by Nestoter** [comment]
@Back team, actualmente comment/create no permite agregar un comentario.
Por favor avisennos cuando quede solucionado de su lado.

**Comment by Eldkaii** [comment]
Quedo pronto. Hay un nuevo servicio comment/CreateFinishedOp.
