### ISSUE TITLE
Backend + Mobile - Notificaciones para el responsable de la operación

### ISSUE THREAD

**Issue by beissoNNN** [calisetpis2019/app.caliset#55]
- [x] Cuando se edita una operación se debe notificar al responsable asignado. (Recordar que se debe mostrar los datos que fueron modificados de la misma.)

- [x] Cuando se crea una op se debe notificar al responsable

- [x] cuando se activa una op se debe notificar al responsable

**Comment by massi12** [comment]
Esto no es frontend mobile.
Permitime que modifique las etiquetas...

**Comment by beissoNNN** [comment]
missclick, mal yo

**Comment by Nestoter** [comment]
Bueno, refloto esto:
![image](https://user-images.githubusercontent.com/37219633/67895387-25f48400-fb39-11e9-8948-a068d4eb4197.png)

**Comment by Eldkaii** [comment]
Pronto. Si alguien lo puede testear y me avisa el resultado ideal.

**Comment by Eldkaii** [comment]
??????????????????????????????????????? Que otro problema tiene esto?

**Comment by massi12** [comment]
Si considerás que está pronto cambia la etiqueta "SIGUE PENDIENTE" por "PRONTO" así queda como "para probar" jajaja

> 
> 
> ??????????????????????????????????????? Que otro problema tiene esto?
