### ISSUE TITLE
DEMO - Web - [Menor] - Activar operación manualmente

### ISSUE THREAD

**Issue by beissoNNN** [calisetpis2019/app.caliset#56]
Ahora el cliente pide que esté esta funcionalidad. Se probó en la demo el boton activar y no anduvo para admin ni para operador.

**Comment by Salameboy** [comment]
Al utilizar el servicio para activar una operacion (Operation/ActivateOperationById) a traves de swagger (en la version liberada) esta no se activo. Sin embargo, en la ultima version del repositorio, esta funcionando. Marco como PRONTO el bug.
