### ISSUE TITLE
DEMO - Web - [Menor] - Buscador en usuarios

### ISSUE THREAD

**Issue by beissoNNN** [calisetpis2019/app.caliset#58]
El buscador en Usuarios debe filtrar por nombre y también apellido.
No debe de ser case sensitive.
Trimear.

**Comment by Nestoter** [comment]
Solicitado a Backend el cambio del servicio que invocamos para que soporte lo solicitado acá.

**Comment by Salameboy** [comment]
Esta filtrando perfecto (no case sensitive), el problema es si haces una busqueda con espacios. Si quiero buscar el usuario "inspector gutierrez" en el keyword el servicio lo traduce a "inspector%2Bgutierrez" en la llamada al servicio, probe mandar en el keyword "inspector+gutierrez" y no me encuentra nada.

**Comment by Eldkaii** [comment]
@Salameboy  lo que pasa que es buscador esta pensado para una sola palabra. Para hacer con mas hay que cambiarlo

**Comment by Salameboy** [comment]
Bien. Entonces esta listo!
