### ISSUE TITLE
DEMO - MOBILE - [Menor] - Scroll de asignaciones invisible

### ISSUE THREAD

**Issue by beissoNNN** [calisetpis2019/app.caliset#62]
Scroll de asignaciones invisible, parece que hay solo una op y en realidad puede haber varias, solo que hay que scrollear.

**Comment by massi12** [comment]
Se solucionó poniendo todo en tabs, así no se presenta más este problema y está toda la pantalla disponible para **activas**, **futuras** y **nuevas**.
