### ISSUE TITLE
DEMO - WEB - [Menor] - Error en fecha y hora de asignación

### ISSUE THREAD

**Issue by beissoNNN** [calisetpis2019/app.caliset#63]
Respecto al error que surgió en la Demo, que se asignó inicio a las 8:30 y fin a 18:30; 
el problema parece que está en la selección de am o pm.
Parece que está tomando 18:30 como 6:30, y tira error de fecha de fin anterior a la de inicio. @Nestoter

**Comment by Nestoter** [comment]
Pronto!
