### ISSUE TITLE
Web - [Crítico] - No se permite crear operaciones luego de loguearse en mobile

### ISSUE THREAD

**Issue by beissoNNN** [calisetpis2019/app.caliset#66]
La secuencia fue la siguiente:
-Admin está logeado en web

-Admin se loguea en mobile para ver si le llegan notificacones por ser responsable a una operación. (se le pide modificar la contraseña como a los inspectores, por lo tanto se reloguea en la web con la nueva pass por las dudas).

-Admin intenta crear operación con él como responsable, y le salta el siguiente error: 
![image](https://user-images.githubusercontent.com/29243394/68076459-8bdc4800-fd93-11e9-84ea-ac906dbf848f.png)

**Comment by Eldkaii** [comment]
Desde el swagger te deja loguearte y asignarte a vos mismo como manager de una operación. Habría
 que ver las 3 áreas juntas a ver donde esta el problema.

**Comment by beissoNNN** [comment]
Esto pasó luego de que agregaran la notificación al responsable al celular, me parece.

**Comment by Eldkaii** [comment]
Tenemos algún progreso de esto? @beissoNNN
