### ISSUE TITLE
Web - [Marginal] - No está andando el cambio automático de estado

### ISSUE THREAD

**Issue by beissoNNN** [calisetpis2019/app.caliset#67]
Se crea una operación Futura, y pasado el tiempo de inicio de la op no se hace el cambio a estado activa. Antes andaba esto.

**Comment by Salameboy** [comment]
Se volvio a subir el demonio con la ultima version que estaba en el repositorio.

**Comment by Eldkaii** [comment]
Che funciona el demonio o no?

**Comment by beissoNNN** [comment]
Sigue sin andar

**Comment by beissoNNN** [comment]
No está andando el demonio

**Comment by Salameboy** [comment]
Se habia subido con un parametro mal, volver a testear.
