### ISSUE TITLE
Web - [Menor] - Quitar asignación - No se actualiza página automáticamente

### ISSUE THREAD

**Issue by beissoNNN** [calisetpis2019/app.caliset#68]
Se desasigna correctamente pero no se actualiza la página, entonces parece que no se hizo nada y al darle de nuevo a asignar te salta error porque ya se desasignó.

**Comment by Nestoter** [comment]
@beissoNNN me pasas captura de pantalla? Yo lo arreglé en un lado, no se donde lo estás viendo vos.

**Comment by beissoNNN** [comment]
Te digo la secuencia que me parece más claro.
Listar usuarios->Boton "ver" en un usuario->Pestaña "asignaciones"->Botón "ver" en una asignación-> Ahí te lista las asignaciones de los usuarios y al darl a "quitar" como que se actualiza pero vuuelve a aparecer.
@Nestoter
