### ISSUE TITLE
Web - [Marginal] - Quitar asignación - No se notifica al responsable

### ISSUE THREAD

**Issue by beissoNNN** [calisetpis2019/app.caliset#69]
La notificación se envía correctamente al usuario desasignado pero no al responsable.

**Comment by Nestoter** [comment]
Buenas, la notificación en el FW fué recortada del alcance (la famosa campanita). ¿Es ese el problema que estás reportando?

**Comment by beissoNNN** [comment]
Se me escapó la etiqueta de frontweb.
Me refería a la notificacion mobile al responsable. 
Como el testeo de esta HU se postergó a esta liberación, recién salto el error de que falta notificar al responsable en este caso también.

**Comment by beissoNNN** [comment]
@Eldkaii @fedeGodCamm @vikgonb

**Comment by Eldkaii** [comment]
Pronto.
