### ISSUE TITLE
Bug - Web - [Menor] - Adjuntos en Usuarios

### ISSUE THREAD

**Issue by jmoreira18** [calisetpis2019/app.caliset#7]
La mayoría de los formularios de alta (no revisé los de edición, pues no está dentro del alcance actual de HUs a implementar) tienen indicados incorrectamente los campos obligatorios.
Por ej (en operador sólo aparece como que los 3 primeros lo son, sin embargo hay varios más):
![image](https://user-images.githubusercontent.com/31781992/65821159-4fec1b00-e208-11e9-9f0e-60bc3d61fce7.png)

**Comment by beissoNNN** [comment]
@Salameboy @Nestoter 
Issue Update:

- En alta usuario faltan los opcionales "especialidad" y "archivos adjjuntos"

- En crear ubicacion todos los campos deberian ser obligatorios. (Nombre, Latitud, Longitud, Radio)

**Comment by Nestoter** [comment]
Agregado campo especialidad. Falta funcionalidad del Backend para subir adjunto.

**Comment by fedeGodCamm** [comment]
Back dio por finalizado

**Comment by beissoNNN** [comment]
Falta ver qué hacer con los adjuntos.
