### ISSUE TITLE
Web - [Marginal] - Error random al cambiar entre pestañas "usuarios" y "operaciones"

### ISSUE THREAD

**Issue by beissoNNN** [calisetpis2019/app.caliset#75]
![image](https://user-images.githubusercontent.com/29243394/68345025-24920100-00cf-11ea-8f6f-0e52d7477245.png)
user: Admin3erLiber@gmail.com
pass: NuevaAdmin3erLiber

Cuando paso de pestañas usuarios a operaciones salta eso.

**Comment by Nestoter** [comment]
Intenté pero no pude reproducir el error.

**Comment by Salameboy** [comment]
En teoria esto se arreglo, hay que volver a testearlo cuando este en el servidor.
