### ISSUE TITLE
Crítico - GPS y registro de horas

### ISSUE THREAD

**Issue by beissoNNN** [calisetpis2019/app.caliset#76]
-Se creó una ubicación en la que se encuentra el celular a utilizar, obteniendo latitud y longitud de google maps.
-Se creó una operación que comenzaba 19:55. y se asignó al inspector  de 19:56 a 20:01
-Se activó operación manualmente.
-Se finalizó operación a las 20:02 y se ingreso un registro de horas con el inspector.
-Se entró al registro de horas del inspector en la web y aparece cruz roja en el campo de la posición.

En swagger hay registros de mi posición desde las 19:58 hasta mas de las 20:00

**Comment by massi12** [comment]
Cual sería el rol de mobile acá? 
Los registros del GPS se mandan siempre desde la app, cada cierto tiempo

**Comment by Salameboy** [comment]
Creo que el problema era solo del front. Se estaba imprimiendo mal la respuesta del back.

**Comment by Eldkaii** [comment]
@beissoNNN @Salameboy  Backend tiene que hacer algo aca o puedo sacarnos de la etiqueta?
