### ISSUE TITLE
Web - [Menor] - Registro de horas, no se muestra operación

### ISSUE THREAD

**Issue by beissoNNN** [calisetpis2019/app.caliset#77]
Campo operación esta en blanco

**Comment by Salameboy** [comment]
Agregue los campos mercaderia y ubicacion, ademas del id que ya esta funcionando.

**Comment by beissoNNN** [comment]
el id de la op no está apareciendo.
La otra opción es identificar la operación como especificó gabriel en slack y es como lo está haciendo mobile tmabién, que es:  id - fecha inicio - tipo - ubicación.
