### ISSUE TITLE
Web - [Menor] - Campo en blanco en tabla de listado de usuarios

### ISSUE THREAD

**Issue by beissoNNN** [calisetpis2019/app.caliset#80]
Campo en blanco en tabla de listado de usuarios

**Comment by Nestoter** [comment]
@beissoNNN nos pasas captura de pantalla de donde ves esto? En la vista de usuarios no veo ningún campo en blanco.

**Comment by beissoNNN** [comment]
> 
> 
> @beissoNNN nos pasas captura de pantalla de donde ves esto? En la vista de usuarios no veo ningún campo en blanco.

![imagen](https://user-images.githubusercontent.com/29243394/68604879-30444580-048a-11ea-8faf-d5fd07201990.png)
@Nestoter 
Ah{i a la izq

**Comment by Nestoter** [comment]
@Salameboy tenes idea de esto? En desarrollo se ve todo bien. En lo que está liberado se ven todos estos errores en la consola 
![image](https://user-images.githubusercontent.com/37219633/68611808-c2077f00-0499-11ea-9564-68456b2af98a.png)
