### ISSUE TITLE
Web - [Crítico] - Ingresar responsable al crear una operación

### ISSUE THREAD

**Issue by beissoNNN** [calisetpis2019/app.caliset#84]
No se están listando bien los responsables posibles a elegir.
1-Se creó un nuevo administrador : ResponsableInactivo@gmail.com  y password: Password1
2-Se logeó con el mismo en mobile y web.
3-Se trató de crear operación con él como responsable y no aparecía en la lista.

**Comment by Eldkaii** [comment]
@beissoNNN esto es de back ?
