### ISSUE TITLE
Web - [Crítico] - no anda Quitar asignación

### ISSUE THREAD

**Issue by beissoNNN** [calisetpis2019/app.caliset#85]
![image](https://user-images.githubusercontent.com/29243394/68730163-ad66dc00-05aa-11ea-9df5-f27b89a48e1c.png)

-Cree operacion (id:1) con responsable Admin4Liber@gmail.com pass: Password1
-Logeé en celular
-Cree Inspector4Liber@gmail.com pass: Password1
-Asigne la operación al inspector.
-Quité asignación al inspector y no se realizó la desasignación. Salto el error de la imagen.

**Comment by Eldkaii** [comment]
Esta pronto para testear.
