### ISSUE TITLE
(4taDemo) - Web - [Menor] - Todos los botones en misma línea

### ISSUE THREAD

**Issue by beissoNNN** [calisetpis2019/app.caliset#87]
No están todos los botones en misma línea.

**Comment by Nestoter** [comment]
@beissoNNN ¿En que vistas detectaste esto?

**Comment by beissoNNN** [comment]
En operaciones futuras @Nestoter

**Comment by Nestoter** [comment]
@beissoNNN acabo de verificar con el usuario administrador en testeo y lo veo bien. ¿Podes validar?
![image](https://user-images.githubusercontent.com/37219633/68805778-3e899180-0643-11ea-8810-836acdf74aa6.png)

**Comment by beissoNNN** [comment]
https://puu.sh/EEj3x/e1f1731f5d.png

depende del tamaño de la pantalla o el zoom parece... lo dejo como pronto, no se..

**Comment by Salameboy** [comment]
Si, depende bastante de la resolucion en que se esta viendo. No pude encontrarle una solucion ya que si se obliga a que los botones esten en una linea puede que otra informacion quede viendose mal.
