### ISSUE TITLE
Web - [Marginal] - Error al subir formulario

### ISSUE THREAD

**Issue by beissoNNN** [calisetpis2019/app.caliset#89]
https://puu.sh/EDVPV/b0334f3ba5.png

tiene que ser algun formato especial?
trat´e con un pdf

**Comment by Nestoter** [comment]
@beissoNNN se puede subir CUALQUIER archivo.

@Salameboy revisé los logs y contré que los archivos se están intentando subir a C:\Users\Admin\Documents\Calidapp\Forms11132019 10346 AM.jpg.
Para arreglarlo hay que agregar en el archivo app.caliset\aspnet-core\src\App.Caliset.Core\Models\Forms\FormManager.cs la \ del final del path y republicar el backend.
