### ISSUE TITLE
Bug - Web - [Marginal] - No se permite crear operación

### ISSUE THREAD

**Issue by jmoreira18** [calisetpis2019/app.caliset#9]
(Esta era crítica porque a Joaquín no le dejaba crear la operación, pero luego probe yo y me dejó. Por las dudas la dejo como marginal)

No se permite crear operación pues no hay estados creados (esto tiene un workaround).

Sin embargo, la lista vacía de estados se muestra así:
![image](https://user-images.githubusercontent.com/31781992/65821092-6c3b8800-e207-11e9-8c94-38d3e13d3a5f.png)

Si se intenta crear una operación, con todos los campos o sólo los obligatorios, se muestra este mensaje de error.
![image](https://user-images.githubusercontent.com/31781992/65821100-8b3a1a00-e207-11e9-9dbb-21e0fc6b591e.png)

**Comment by beissoNNN** [comment]
ahora no me deja crear la operacion.
se rellenaron todos los campos.
las ubicaciones se siguen mostrando por id.
El título de la vista de crear la ooperación sigue diciendo " Crear Ubicación".
![image](https://user-images.githubusercontent.com/29243394/66089913-97034480-e557-11e9-9047-1e9c2dd91f89.png)
