### ISSUE TITLE
Web - [Menor] - No se puede activar manualmente una operación Finalizada

### ISSUE THREAD

**Issue by beissoNNN** [calisetpis2019/app.caliset#90]
No aparece el botón al listar las finalizadas.

**Comment by beissoNNN** [comment]
esto creo que nunca se pudo hacer.. pero no tendría sentido que sí? Si finalizas una por error marchaste...

**Comment by Salameboy** [comment]
No se pueden activar operaciones finalizadas, es parte de los requerimientos.
