### ISSUE TITLE
Web+Mobile - [Marginal] - Id de muestra en WEB no coincide con la generada en Mobile

### ISSUE THREAD

**Issue by beissoNNN** [calisetpis2019/app.caliset#91]
Al registrar una muestra no coincide el id mostrado en la app mobile con la que se lista en la web.
Por ejemplo en la app se despliega un mensaje diciendo que se creó muestra con id Operation1Sample3, y esa misma en la web figura con id 4. Deberían las dos decir 4 o 3.

**Comment by Eldkaii** [comment]
El campo que hay que mostrar en la Web no es el Id sino el IdSample.

**Comment by beissoNNN** [comment]
@Nestoter @Salameboy vieron eso que puso emilio? Se está imprimiendo el id de la muestra registrada, no el sample. No se tendría que mostrar las dos cosas?
