### ISSUE TITLE
Web - [Menor] - Mensaje de error al entrar a vista de formularios desde un Operador

### ISSUE THREAD

**Issue by beissoNNN** [calisetpis2019/app.caliset#92]
![image](https://user-images.githubusercontent.com/29243394/68822042-9b4e7180-066e-11ea-99ed-1c475901e76e.png)

Que aparezca un error está bien, ya que la funcionalidad es solamente para admins, pero el error debería de estar en español. La otra opción es sacarle la pestaña Formularios a los operadores.

**Comment by Nestoter** [comment]
@fedeGodCamm @vikgonb @Eldkaii ¿Pueden agregarle los permisos a los usuarios Operador?
![image](https://user-images.githubusercontent.com/37219633/68854096-18530880-06ba-11ea-9e68-70a250305914.png)
