### ISSUE TITLE
WEB - [Menor] - Listar usuarios, último login.

### ISSUE THREAD

**Issue by beissoNNN** [calisetpis2019/app.caliset#97]
Cambiar la fecha de ultimo login cuando recién se crea (01/01/0001, 00:00)

**Comment by Nestoter** [comment]
@beissoNNN no entiendo bien, ¿donde tenemos que cambiar esa fecha?

**Comment by Nestoter** [comment]
Ta ya lo vi, eso estaba andando, veo que pasó,

**Comment by beissoNNN** [comment]
era ponerle otra cosa para aclarar que aun no se logueo en web. Consultalo con nacho sino, que fue quien sugirio cambio
